export function throwAnException(): void {
  throw new Error("I am an exception");
}
